micronaut:
  application:
    name: stockApplication

datasources:
  default:
    dialect: H2
    password: ""
    username: sa
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
jpa:
  default:
    packages-to-scan:
      - 'br.com.rspinfotec.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

